### ISSUE TITLE
Feature Request: Find total Time of selected range in playlist

### ISSUE THREAD

**Issue by karanshah229** [sharatsachin/ytplaylist-len#14]
Implement a feature where user can also specify the range of videos instead of the entire playlist
Default values would be entire range of playlist

**Comment by Theskyspace** [comment]
I would like to work on this issue. Is this still open?

**Comment by karanshah229** [comment]
Yes, it is still open

**Comment by Theskyspace** [comment]
But I'm not sure if the maintainer of this project is still active. Because I had an issue while setting the env.
I'll try once more anyway cause this project sounds interesting to me

**Comment by sharatsachin** [comment]
Hey guys. I could do this myself, but I don't want to because there is a daily YouTube API limit, and this app is already at the limit. I'd add that feature, people would use it more, and then the app itself would stop working. That's why there is a 500 video limit too.

**Comment by Theskyspace** [comment]
Okay Thanks bro,
For making it clear 
Chears

**Comment by karanshah229** [comment]
- [ ] Why don't you create multiple apps and load balance between 

- [ ] Or you can just write some instructions to fork this repo and host it individually

- Eg: https://github.com/anuraghazra/github-readme-stats
- He uses Vercel and has instructions for people to host is individually because of the API limit too

**Comment by sharatsachin** [comment]
Hey @karanshah229 ! Thanks for the suggestions. 
However, I'm talking about the YouTube API limits here, and they specifically forbid creating multiple keys for the same app in their ToS. 
As for option 2, I'm doing that already. The source code is available here, and multiple people have made clones of this already, you can google "ytplaylist-len" to see. Also, on the site, I offer a link to a Colab notebook, that you can open and enter your own API key to kinda have your own version of the app.

**Comment by karanshah229** [comment]
Works!
