### ISSUE TITLE
Can I deploy this on a telegram bot ?

### ISSUE THREAD

**Issue by Manasroxx** [sharatsachin/ytplaylist-len#15]
The title might be enough an expanation😅😅

**Comment by pvcodes** [comment]
of course, use web scrapping using [Beautiful Soup](https://beautiful-soup-4.readthedocs.io/en/latest/) or regular [requests](https://docs.python-requests.org/en/latest/) module etc...

**Comment by pvcodes** [comment]
Or just use YT's API to get direct data for ur bot :)
