### ISSUE TITLE
Internal Server Error after clicking Get Length

### ISSUE THREAD

**Issue by Nicofisi** [sharatsachin/ytplaylist-len#2]
Hello, so I googled something and a link to your app hosted on https://ytplaylist-len.herokuapp.com/ came up, I assume it's the official instance. 

I've tried to get lengths of the following two playlists:
https://www.youtube.com/playlist?list=PLxsBwxT0vz00flofgvggZHP4mFwYNsjXY
https://www.youtube.com/playlist?list=PLxsBwxT0vz01LuuZiA7OWT2araiysEoxY

but all I get is an all-white site with the following black text:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Thank you for support and cheers

**Comment by TurretAA12** [comment]
I have the same error too.

**Comment by sharatsachin** [comment]
Hey guys, could you tell me the exact time at which you had this issue, and the time zone you are in? 
This app has become much much more popular than I intended.

**Comment by TurretAA12** [comment]
Yes, the issue is fixed last I checked
