### ISSUE TITLE
Playlist data is wrong when some videos are private

### ISSUE THREAD

**Issue by AhmedNazir** [sharatsachin/ytplaylist-len#35]
for example, if any playlist has 32 videos but 12 videos is private.

ytplaylist shows total 32 video but actual 20 videos is available for this tool. Instead of using 20, ytplaylist uses 32 to calculate next numerical calculation like Average length of video.

https://ytplaylist-len.us/ shows right numerical data.

**Comment by sanketkamta** [comment]
The issue is handled here - https://youtube-playlist-length-e8xu.onrender.com/

**Comment by sharatsachin** [comment]
@AhmedNazir Please check if this is fixed as per the latest deployment.
