### ISSUE TITLE
Feature: Add option for custom playback speed length

### ISSUE THREAD

**Issue by bgiesing** [sharatsachin/ytplaylist-len#37]
It's handy that the site shows the total length when using the default YouTube playback speed options but many people use extensions to use custom speeds greater than 2x so it might be nice to let you enter in a manual speed like "3.5" and it will update to show you said time.

**Comment by sanketkamta** [comment]
The issue is handled here - https://youtube-playlist-length-e8xu.onrender.com/

**Comment by sharatsachin** [comment]
@bgiesing This has been added in the latest deployment.
