### ISSUE TITLE
possible to make this a chrome extension?

### ISSUE THREAD

**Issue by jBbL81** [sharatsachin/ytplaylist-len#4]
any chance this could be made into a chrome extension? i tried all the available ones on the chrome store and not a single one worked.

thanks!

**Comment by sharatsachin** [comment]
I don't think so, this works server side while the chrome extensions usually work client side. I'd hit the API limits. 
Btw, did you try [this one?](https://chrome.google.com/webstore/detail/youtube-playlist-duration/pijbakhgmhhadeakaocjfockpndcpobk?hl=en)
