### ISSUE TITLE
Update UI of the web page

### ISSUE THREAD

**Issue by spiyush0212** [sharatsachin/ytplaylist-len#7]
Hello, I believe that this is a great website but the UI of the homepage is not appealing. I have experience in designing web pages and interfaces. If you want I can create a nice front end for your webpage. Should I?

**Comment by XtremePwnership** [comment]
Hey @sharatsachin just wanted to say love your web app, extremely useful & snappy. Thanks a lot! :)

**Comment by sharatsachin** [comment]
@spiyush0212 Thanks, but I feel the interface is okay for the purpose it serves, so there's no need.

@XtremePwnership Good to know, thanks for reaching out! 😄
